name: Generate Snake

on:
  # 每天午夜自动运行
  schedule:
    - cron: "0 0 * * *" 
  # 允许你手动点击按钮触发
  workflow_dispatch:
  # 每次 push 到主分支时也刷新一下
  push:
    branches:
    - master
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 生成 SVG 动画
      - name: Generate Snake Game from contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      # 将生成的文件推送到 output 分支
      - name: Push snake to the output branch
        uses: crazy-max/gh-action-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
